### ISSUE TITLE
Proposal: Project Details

### ISSUE THREAD

**Issue by denrase** [getsentry/sentry-mobile-release-health-app#213]
# Goal

- Align the app better with the current web project details page.
- This would move us away from the issue that most reviewers now have, namely that the app is only showing session data, which seems to not be enough for a large part of the apps users. Hence, the bad rating right now.
- I also think that the current layout with the large cards at the top for the projects does not lend itself well for the project details visualisation if we want to show more than just session data.
- We should also consider showing a basic issue list and some details.

## Main Screen

- Button at the top of the app with selected project.
    - When tapped, list of all projects is presented.
    - Starred projects are at the top.
    - Ability to star projects inline.
- Buttons at the top to switch environments and date ranges.
- Show most important stats with large text
    - Crash free sessions
    - Number of releases
    - Appdex
    - If they are not present, show "Start Setup" button and link to docs
- Large graphs as the center of the app
    - Crash Free Sessions
    - Apdex
    - Failure Rate
    - Transactions Per Minute
    - Number Of Errors
    - Number of Sessions
    - Number of Transactions

## Issues (Later/Optional)

- "View All Issues"
    - One of the most requested things in the review feedback we get.
    - Basic list of all issues.
    - Very basic issue details with linking into the browser for the full view.

## UI Prototype

![_Projcts](https://user-images.githubusercontent.com/3984453/133622369-f01568e1-67c6-40a8-8dee-68c7e1ec1231.png)

**Comment by denrase** [comment]
@matejminar @HazAT I'd need your input on this. Think this is the way to go if we want to show more of the project data that we have and not stray too far from the main product.

**Comment by matejminar** [comment]
Very reasonable changes 👍

Let's sync on what those graphs should be.

I think we are missing some charts that users claimed very valuable:
- Crash Free Users 
- Number of Users
- Session Duration

On the other, we might not need some of the graphs from the description (so that it's not overwhelming).

**Comment by denrase** [comment]
@denrase Sounds good to me, first things first.
@matejminar Yeah i agree that we probably don't need all the graphs that the web version offers. Best we prioritise which ones are the most important and focus on those.

**Comment by denrase** [comment]
Some intermediate progress

<img width="721" alt="Bildschirmfoto 2022-02-07 um 15 33 02" src="https://user-images.githubusercontent.com/3984453/152809582-fefabd3a-bf0b-4af5-a0da-500ee94560d4.png">

**Comment by Jesse-Box** [comment]
@denrase shall we close this issue for now?
